/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SecureDocChainInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "accessLog"
      | "batchGrantAccess"
      | "createDocument"
      | "documentExists"
      | "documents"
      | "getAccessLevel"
      | "getAccessLog"
      | "getDocumentState"
      | "grantAccess"
      | "hasAccess"
      | "logAccess"
      | "owner"
      | "pause"
      | "paused"
      | "renounceOwnership"
      | "revokeAccess(bytes32,address,string)"
      | "revokeAccess(bytes32,address)"
      | "transferOwnership"
      | "unpause"
      | "updateDocument"
      | "verifyIntegrity"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AccessGranted"
      | "AccessRevoked"
      | "DocumentAccessed"
      | "DocumentCreated"
      | "DocumentUpdated"
      | "OwnershipTransferred"
      | "Paused"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "accessLog",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "batchGrantAccess",
    values: [BytesLike, AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "createDocument",
    values: [BytesLike, string, string, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "documentExists",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "documents",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAccessLevel",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAccessLog",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDocumentState",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantAccess",
    values: [BytesLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasAccess",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "logAccess",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeAccess(bytes32,address,string)",
    values: [BytesLike, AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeAccess(bytes32,address)",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateDocument",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyIntegrity",
    values: [BytesLike, string]
  ): string;

  decodeFunctionResult(functionFragment: "accessLog", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "batchGrantAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createDocument",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "documentExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "documents", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAccessLevel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAccessLog",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDocumentState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasAccess", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "logAccess", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeAccess(bytes32,address,string)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeAccess(bytes32,address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateDocument",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyIntegrity",
    data: BytesLike
  ): Result;
}

export namespace AccessGrantedEvent {
  export type InputTuple = [
    docHash: BytesLike,
    grantee: AddressLike,
    level: BigNumberish,
    ts: BigNumberish
  ];
  export type OutputTuple = [
    docHash: string,
    grantee: string,
    level: bigint,
    ts: bigint
  ];
  export interface OutputObject {
    docHash: string;
    grantee: string;
    level: bigint;
    ts: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AccessRevokedEvent {
  export type InputTuple = [
    docHash: BytesLike,
    grantee: AddressLike,
    newKeyVersion: BigNumberish,
    ts: BigNumberish
  ];
  export type OutputTuple = [
    docHash: string,
    grantee: string,
    newKeyVersion: bigint,
    ts: bigint
  ];
  export interface OutputObject {
    docHash: string;
    grantee: string;
    newKeyVersion: bigint;
    ts: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DocumentAccessedEvent {
  export type InputTuple = [
    docHash: BytesLike,
    accessor: AddressLike,
    ts: BigNumberish
  ];
  export type OutputTuple = [docHash: string, accessor: string, ts: bigint];
  export interface OutputObject {
    docHash: string;
    accessor: string;
    ts: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DocumentCreatedEvent {
  export type InputTuple = [
    docHash: BytesLike,
    cid: string,
    owner: AddressLike,
    docType: string,
    ipTimestamp: boolean,
    ts: BigNumberish
  ];
  export type OutputTuple = [
    docHash: string,
    cid: string,
    owner: string,
    docType: string,
    ipTimestamp: boolean,
    ts: bigint
  ];
  export interface OutputObject {
    docHash: string;
    cid: string;
    owner: string;
    docType: string;
    ipTimestamp: boolean;
    ts: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DocumentUpdatedEvent {
  export type InputTuple = [
    docHash: BytesLike,
    newCid: string,
    version: BigNumberish,
    keyVersion: BigNumberish,
    ts: BigNumberish
  ];
  export type OutputTuple = [
    docHash: string,
    newCid: string,
    version: bigint,
    keyVersion: bigint,
    ts: bigint
  ];
  export interface OutputObject {
    docHash: string;
    newCid: string;
    version: bigint;
    keyVersion: bigint;
    ts: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SecureDocChain extends BaseContract {
  connect(runner?: ContractRunner | null): SecureDocChain;
  waitForDeployment(): Promise<this>;

  interface: SecureDocChainInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  accessLog: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  batchGrantAccess: TypedContractMethod<
    [_dh: BytesLike, _users: AddressLike[], _levels: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  createDocument: TypedContractMethod<
    [
      _docHash: BytesLike,
      _cid: string,
      _docType: string,
      _expiry: BigNumberish,
      _ipTimestamp: boolean
    ],
    [void],
    "nonpayable"
  >;

  documentExists: TypedContractMethod<[_dh: BytesLike], [boolean], "view">;

  documents: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, bigint, string, bigint, boolean] & {
        ipfsCID: string;
        owner: string;
        version: bigint;
        keyVersion: bigint;
        timestamp: bigint;
        docType: string;
        expiry: bigint;
        ipTimestamp: boolean;
      }
    ],
    "view"
  >;

  getAccessLevel: TypedContractMethod<
    [_dh: BytesLike, _user: AddressLike],
    [bigint],
    "view"
  >;

  getAccessLog: TypedContractMethod<[_dh: BytesLike], [string[]], "view">;

  getDocumentState: TypedContractMethod<
    [_dh: BytesLike],
    [
      [string, string, bigint, bigint, bigint, string, bigint, boolean] & {
        cid: string;
        owner: string;
        version: bigint;
        keyVersion: bigint;
        timestamp: bigint;
        docType: string;
        expiry: bigint;
        ipTimestamp: boolean;
      }
    ],
    "view"
  >;

  grantAccess: TypedContractMethod<
    [_dh: BytesLike, _user: AddressLike, _level: BigNumberish],
    [void],
    "nonpayable"
  >;

  hasAccess: TypedContractMethod<
    [_dh: BytesLike, _user: AddressLike],
    [[boolean, bigint]],
    "view"
  >;

  logAccess: TypedContractMethod<[_dh: BytesLike], [void], "nonpayable">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  "revokeAccess(bytes32,address,string)": TypedContractMethod<
    [_dh: BytesLike, _user: AddressLike, _newCid: string],
    [void],
    "nonpayable"
  >;

  "revokeAccess(bytes32,address)": TypedContractMethod<
    [_dh: BytesLike, _user: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateDocument: TypedContractMethod<
    [_dh: BytesLike, _newCid: string],
    [void],
    "nonpayable"
  >;

  verifyIntegrity: TypedContractMethod<
    [_dh: BytesLike, _cid: string],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "accessLog"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "batchGrantAccess"
  ): TypedContractMethod<
    [_dh: BytesLike, _users: AddressLike[], _levels: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createDocument"
  ): TypedContractMethod<
    [
      _docHash: BytesLike,
      _cid: string,
      _docType: string,
      _expiry: BigNumberish,
      _ipTimestamp: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "documentExists"
  ): TypedContractMethod<[_dh: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "documents"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, bigint, string, bigint, boolean] & {
        ipfsCID: string;
        owner: string;
        version: bigint;
        keyVersion: bigint;
        timestamp: bigint;
        docType: string;
        expiry: bigint;
        ipTimestamp: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAccessLevel"
  ): TypedContractMethod<
    [_dh: BytesLike, _user: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAccessLog"
  ): TypedContractMethod<[_dh: BytesLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getDocumentState"
  ): TypedContractMethod<
    [_dh: BytesLike],
    [
      [string, string, bigint, bigint, bigint, string, bigint, boolean] & {
        cid: string;
        owner: string;
        version: bigint;
        keyVersion: bigint;
        timestamp: bigint;
        docType: string;
        expiry: bigint;
        ipTimestamp: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantAccess"
  ): TypedContractMethod<
    [_dh: BytesLike, _user: AddressLike, _level: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasAccess"
  ): TypedContractMethod<
    [_dh: BytesLike, _user: AddressLike],
    [[boolean, bigint]],
    "view"
  >;
  getFunction(
    nameOrSignature: "logAccess"
  ): TypedContractMethod<[_dh: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeAccess(bytes32,address,string)"
  ): TypedContractMethod<
    [_dh: BytesLike, _user: AddressLike, _newCid: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeAccess(bytes32,address)"
  ): TypedContractMethod<
    [_dh: BytesLike, _user: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateDocument"
  ): TypedContractMethod<
    [_dh: BytesLike, _newCid: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyIntegrity"
  ): TypedContractMethod<[_dh: BytesLike, _cid: string], [boolean], "view">;

  getEvent(
    key: "AccessGranted"
  ): TypedContractEvent<
    AccessGrantedEvent.InputTuple,
    AccessGrantedEvent.OutputTuple,
    AccessGrantedEvent.OutputObject
  >;
  getEvent(
    key: "AccessRevoked"
  ): TypedContractEvent<
    AccessRevokedEvent.InputTuple,
    AccessRevokedEvent.OutputTuple,
    AccessRevokedEvent.OutputObject
  >;
  getEvent(
    key: "DocumentAccessed"
  ): TypedContractEvent<
    DocumentAccessedEvent.InputTuple,
    DocumentAccessedEvent.OutputTuple,
    DocumentAccessedEvent.OutputObject
  >;
  getEvent(
    key: "DocumentCreated"
  ): TypedContractEvent<
    DocumentCreatedEvent.InputTuple,
    DocumentCreatedEvent.OutputTuple,
    DocumentCreatedEvent.OutputObject
  >;
  getEvent(
    key: "DocumentUpdated"
  ): TypedContractEvent<
    DocumentUpdatedEvent.InputTuple,
    DocumentUpdatedEvent.OutputTuple,
    DocumentUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "AccessGranted(bytes32,address,uint8,uint256)": TypedContractEvent<
      AccessGrantedEvent.InputTuple,
      AccessGrantedEvent.OutputTuple,
      AccessGrantedEvent.OutputObject
    >;
    AccessGranted: TypedContractEvent<
      AccessGrantedEvent.InputTuple,
      AccessGrantedEvent.OutputTuple,
      AccessGrantedEvent.OutputObject
    >;

    "AccessRevoked(bytes32,address,uint256,uint256)": TypedContractEvent<
      AccessRevokedEvent.InputTuple,
      AccessRevokedEvent.OutputTuple,
      AccessRevokedEvent.OutputObject
    >;
    AccessRevoked: TypedContractEvent<
      AccessRevokedEvent.InputTuple,
      AccessRevokedEvent.OutputTuple,
      AccessRevokedEvent.OutputObject
    >;

    "DocumentAccessed(bytes32,address,uint256)": TypedContractEvent<
      DocumentAccessedEvent.InputTuple,
      DocumentAccessedEvent.OutputTuple,
      DocumentAccessedEvent.OutputObject
    >;
    DocumentAccessed: TypedContractEvent<
      DocumentAccessedEvent.InputTuple,
      DocumentAccessedEvent.OutputTuple,
      DocumentAccessedEvent.OutputObject
    >;

    "DocumentCreated(bytes32,string,address,string,bool,uint256)": TypedContractEvent<
      DocumentCreatedEvent.InputTuple,
      DocumentCreatedEvent.OutputTuple,
      DocumentCreatedEvent.OutputObject
    >;
    DocumentCreated: TypedContractEvent<
      DocumentCreatedEvent.InputTuple,
      DocumentCreatedEvent.OutputTuple,
      DocumentCreatedEvent.OutputObject
    >;

    "DocumentUpdated(bytes32,string,uint256,uint256,uint256)": TypedContractEvent<
      DocumentUpdatedEvent.InputTuple,
      DocumentUpdatedEvent.OutputTuple,
      DocumentUpdatedEvent.OutputObject
    >;
    DocumentUpdated: TypedContractEvent<
      DocumentUpdatedEvent.InputTuple,
      DocumentUpdatedEvent.OutputTuple,
      DocumentUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
