/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as openzeppelin from "./@openzeppelin";
export type { openzeppelin };
import type * as contracts from "./contracts";
export type { contracts };
export * as factories from "./factories";
export type { Ownable } from "./@openzeppelin/contracts/access/Ownable";
export { Ownable__factory } from "./factories/@openzeppelin/contracts/access/Ownable__factory";
export type { Pausable } from "./@openzeppelin/contracts/utils/Pausable";
export { Pausable__factory } from "./factories/@openzeppelin/contracts/utils/Pausable__factory";
export type { SecureDocChain } from "./contracts/SecureDocChain";
export { SecureDocChain__factory } from "./factories/contracts/SecureDocChain__factory";
